fix die() make_rundir()

diff --git a/scripts/m5run.in b/scripts/m5run.in
--- a/scripts/m5run.in
+++ b/scripts/m5run.in
@@ -155,10 +155,12 @@ cleanup () {
 trap ':; cleanup' 0
 
 die () {
+    s=$?
+    test $s -eq 0 && s=1
     if test $# -gt 0 ; then
         printf "%s\n" "$@" >&2
     fi
-    exit 1
+    exit $s
 }
 
 usage () {
@@ -182,11 +184,20 @@ gen_auth_code () {
 
 make_run_dir () {
     if test -z "$run_dir" ; then
-        run_dir="$(umask 077; mktemp -d -p . m5.XXXXXXXXX)"
-        cu_run_dir="$run_dir"
-        test -n "$run_dir" || die "mktemp failed"
+        # Create a (secure) tmp directory for tmp files.
+        {
+            tmp=`(umask 077 && mktemp -d "./m5.XXXXXX") 2>/dev/null` &&
+                test -d "$tmp"
+        } || {
+            tmp=./m5.$$-$RANDOM
+            (umask 077 && mkdir "$tmp")
+        } || die "cannot create a temporary directory in ."
+        run_dir="$tmp"
+        cu_run_dir="$tmp"
+    elif test ! -d "$run_dir" || test ! -w "$run_dir" ; then
+        die "bad run_directory:  $run_dir"
     else
-        mkdir "$run_dir" || die "mkdir failed"
+        cu_run_dir=
     fi
 }
 
