death to semicolons

diff --git a/scripts/m5run.in b/scripts/m5run.in
--- a/scripts/m5run.in
+++ b/scripts/m5run.in
@@ -219,7 +219,7 @@ verbose_printf () {
 }
 
 gen_auth_code () {
-    auth_code=$(dd if=/dev/urandom count=1 ibs=28 status=none | shasum -b -a 224) || die;
+    auth_code=$(dd if=/dev/urandom count=1 ibs=28 status=none | shasum -b -a 224) || die
     auth_code=`expr "X$auth_code" : 'X\([^ ]*\)'`
 }
 
@@ -251,7 +251,7 @@ lib_find () {
         case $base in #(
             *$ext) :
                 exts=
-                break;
+                break
                 ;; #(
             *) : ;;
         esac
@@ -279,14 +279,14 @@ lib_find () {
 		        test -r "$full" || die "not readable: $full"
 		        break 2
 	            fi
-	        done;
+	        done
 	        full=
             done
             IFS=$save_IFS
             ;;
     esac
-    test "$full" || return 1;
-    return 0;
+    test "$full" || return 1
+    return 0
 }
 
 lib_template_find () {
@@ -304,7 +304,7 @@ lib_template_find () {
     if test ! -f "$full.bot" || test ! -r "$full.bot" ; then
         die "file not found: $full.bot"
     fi
-    return 0;
+    return 0
 }
 
 db_middle () {
@@ -510,7 +510,7 @@ wait_error=
 
 wait_log () {
     # local toss fst snd thd goal
-    test "$moo_log_pipe" || return 0;
+    test "$moo_log_pipe" || return 0
     if $do_shconn ; then
         goal="shellport"
     elif $do_player ; then
@@ -565,7 +565,7 @@ wait_log () {
                     ;; #(
                 SHUTDOWN:) :
                     if test "$goal" = "$fst"; then
-                        goal= ;
+                        goal=
                     fi
                     wait_error="premature shutdown"
                     break
@@ -576,8 +576,8 @@ wait_log () {
         { cat - >/dev/null 0<&5 5<&- & } 5<&0
         exec 5>&-
     } <"$moo_log_pipe"
-    test "$goal" && return 1;
-    return 0;
+    test "$goal" && return 1
+    return 0
 }
 
 sh_connect () {
@@ -797,7 +797,8 @@ Informational options:
   -v, +v, --verbose                 be extra chatty on stderr
   -n, +n, --dry-run                 validate command line and exit
   -h, +h, -?, --help                print this text and exit
-  -V, +V, --version, --about        print version info and exit
+  -V, +V, --version                 print version info and exit
+      --about                       print detailed version info and exit
 
  short options cannot be combined, parameters are required
 
@@ -1055,7 +1056,7 @@ push_code () {
 
 conflicts=
 conflict () {
-    usage "conflicting options:  $conflicts vs. $1";
+    usage "conflicting options:  $conflicts vs. $1"
 }
 
 #### Gather command line args
@@ -1178,7 +1179,7 @@ while test "$#" -gt 0 ; do
                 shift
             done
             set --
-            break;
+            break
             ;; #(
         --expr=*) :
             push_code expr "$argument"
@@ -1413,7 +1414,7 @@ if test "$file_db" ; then
 
     # resolve filename
     if test "$file_db" != "-"; then
-        lib_find "$file_db" .db || die "--dbfile|-d not found: $file_db";
+        lib_find "$file_db" .db || die "--dbfile|-d not found: $file_db"
         file_db="$full"
     fi
 
@@ -1482,22 +1483,30 @@ else
     # no moo rules out a whole lot of activities
     conflicts="--no-moo|-M"
 
-    test "$final_log" && conflict "-l|--log";
-    test "$final_db"  && conflict "-o|--out-db";
+    test "$final_log" && conflict "-l|--log"
+    test "$final_db"  && conflict "-o|--out-db"
     if test "$moo_port" || test "$listen_zcount" -gt 0 || test "$listen_fixed"; then
         conflict "-p|--listen"
     fi
     test "$moo_args"    && conflict "-- args..."
-    test "$template_db" && conflict "-t|--db";
-    test "$file_db"     && conflict "-d|--dbfile";
-    test "$code_count" -gt 0  && conflict "-f|--code-file|-e|--expr";
+    test "$template_db" && conflict "-t|--db"
+    test "$file_db"     && conflict "-d|--dbfile"
+    test "$code_count" -gt 0  && conflict "-f|--code-file|-e|--expr"
     case $do_shutdown in #(
-      exit*) : do_shutdown=false ;; #(
-          *) : conflict "+H|-H|--(no)-shutdown" ;;
+      exit*) :
+        do_shutdown=false
+        ;; #(
+      *) :
+        conflict "+H|-H|--(no)-shutdown"
+        ;;
     esac
     case $do_player in #(
-      exit*) : do_player=false ;; #(
-          *) : conflict "+P|-P|--(no)-player" ;;
+      exit*) :
+        do_player=false
+        ;; #(
+      *) :
+        conflict "+P|-P|--(no)-player"
+        ;;
     esac
 fi
 
