redo indirect variables, add M5_FOREACH_CODE and M5_FOREACH_LISTENER

diff --git a/scripts/m5run.in b/scripts/m5run.in
--- a/scripts/m5run.in
+++ b/scripts/m5run.in
@@ -56,6 +56,24 @@ as_nl='
 # splitting by setting IFS to empty value.)
 IFS=" ""	$as_nl"
 
+# as_fn_arith ARG...
+# ------------------
+# Perform arithmetic evaluation on the ARGs, and store the result in the
+# global $as_val. Take advantage of shells that can avoid forks. The arguments
+# must be portable across $(()) and expr.
+if (eval "test \$(( 1 + 1 )) = 2") 2>/dev/null; then :
+  eval 'as_fn_arith ()
+  {
+    as_val=$(( $* ))
+  }'
+else
+  as_fn_arith ()
+  {
+    as_val=`expr "$@" || test $? -eq 1`
+  }
+fi # as_fn_arith
+
+
 if expr a : '\(a\)' >/dev/null 2>&1 &&
    test "X`expr 00001 : '.*\(...\)'`" = X001; then
   as_expr=expr
@@ -125,10 +143,10 @@ final_db=
 final_log=
 do_shutdown=MAYBE
 
-do_stdin_code=
+do_stdin_code=false
 code_count=0
-# _code_what$N = file|expr
-# _code_source$N = filename|expression
+# _code_what$N = 'file'|'stdin'|'expr'
+# _code_source$N = actual filename or expression
 
 do_runmoo=MAYBE
 do_shconn=MAYBE
@@ -293,36 +311,44 @@ db_middle () {
         printf "$moo_port,"'"#0"'
         comma=:
     fi
-    if test "$listen_fixed" || test "$listen_zcount" -gt 0; then
-        for z in $listen_fixed; do
-            lname="$(eval printf "%s" '"$'"_listen_$z"'"')"
-            $comma && printf ','
-            if test "$shell_port" && test "$shell_port" -eq "$z"; then
-                printf 'shell_port='
-            fi
-            printf 'listen('
-            for l in $lname ; do
-                printf '`{%s,o="%s"}[1]!ANY=>1'"' &&" $l $l
-            done
-            printf '%s' "raise(E_PROPNF),$z,1),o"
-            comma=:
+    for port in $listen_fixed; do
+        eval lname=\$_listen_$port
+        is_shell_port=false
+        test "$shell_port" && test "$shell_port" -eq "$port" &&
+            is_shell_port=:
+
+        $comma && printf ','
+        if $is_shell_port ; then
+            printf 'shell_port='
+        fi
+        printf 'listen('
+        for l in $lname ; do
+            printf '`{%s,o="%s"}[1]!ANY=>1'"' &&" $l $l
         done
-        z=1
-        while test "$z" -le "$listen_zcount"; do
-            lname="$(eval printf "%s" '"$'"_listen_z$z"'"')"
-            $comma && printf ','
-            if test "$shell_port" && test "$shell_listener" = "$lname" && test "$shell_port" -eq 0 ; then
-                printf 'shell_port='
-            fi
-            printf 'listen('
-            for l in $lname ; do
-                printf '`{%s,o="%s"}[1]!ANY=>1'"' &&" $l $l
-            done
-            printf '%s' 'raise(E_PROPNF),0,1),o'
-            comma=:
-            z=$((z+1))
+        printf '%s' "raise(E_PROPNF),$port,1),o"
+        comma=:
+    done
+    port=0
+    z=1
+    while test "$z" -le "$listen_zcount"; do
+        eval lname=\$_listen_z$z
+        is_shell_port=false
+        test "$shell_port" && test "$shell_port" -eq "$port" &&
+            test "$shell_listener" = "$lname" &&
+            is_shell_port=:
+
+        $comma && printf ','
+        if $is_shell_port ; then
+            printf 'shell_port='
+        fi
+        printf 'listen('
+        for l in $lname ; do
+            printf '`{%s,o="%s"}[1]!ANY=>1'"' &&" $l $l
         done
-    fi
+        printf '%s' "raise(E_PROPNF),$port,1),o"
+        comma=:
+        as_fn_arith $z \+ 1 && z=$as_val
+    done
     printf '};run_info[$+1..$]={"listeners",listeners,@shell_port?{"shell_port",shell_port}|{}};'
     printf 'server_log(tostr("ri ",toliteral(run_info)));'
     printf 'if(shell_port)server_log(tostr("shellport ",shell_port));endif '
@@ -333,26 +359,29 @@ db_middle () {
     printf 'args = {%s};' "$moo_args"
     z=1
     while test "$z" -le "$code_count"  ; do
-        eval w='"$'"_code_what$z"'"'
-        eval v='"$'"_code_source$z"'"'
+        code_this="_code_source$z"
+        eval code_source=\$$code_this
+        eval w=\$_code_what$z
         case $w in #(
-            expr) :
-                printf "%s" "$v"
-                ;; #(
             file) :
-                if test "$v" != "-"; then
-                    cat "$v"
-                elif test "$do_dryrun" ; then
+                cat "$code_source"
+                printf ";\n"
+                ;; #(
+            stdin) :
+                if test "$do_dryrun" ; then :
                     printf "\n<< code from standard input >>\n"
                 else
                     cat <&5
                     exec 5>&-
+                    printf ";\n"
                 fi
+                ;; #(
+            expr) :
+                printf "%s\n" "$code_source;"
                 ;; #(
             *) : ;;
         esac
-        z=$((z+1))
-        printf ";\n"
+        as_fn_arith $z \+ 1 && z=$as_val
     done
     test -n "$do_shutdown" &&
         printf "%s\n" 'finally`boot_player(player)!ANY'"'"';shutdown();endtry '
@@ -435,7 +464,7 @@ run_moo () {
     elif test -n "$template_db" ; then
         if $can_dev_stdin ; then
             in_db="/dev/stdin"
-            if test "$do_stdin_code" ; then
+            if $do_stdin_code ; then
                 { cat_db | logged_moo & } 5<&0 0<&-
                 exec 5>&-
             else
@@ -444,7 +473,7 @@ run_moo () {
         else
             in_db="${run_dir}/pipe_d"
             mkfifo -m600 "$in_db" || die
-            if test "$do_stdin_code" ; then
+            if $do_stdin_code ; then
                 { { cat_db >"$in_db" ; rm -f "$in_db" ; } & } 5<&0 0<&-
                 exec 5>&-
             else
@@ -773,14 +802,14 @@ describe_for_dryrun () {
     printf "M5 Version:  %s\n" "$m5_version"
     test "$do_verbose" && printf "  being verbose (-v|--verbose)\n"
     test "$do_help" && {
-        printf "  (print helptext (-h|--help)\n" ; exit
+        printf "  print helptext (-h|--help)\n" ; exit
     }
     test "$do_version" && {
-        printf "  (print version  (-V|--version)\n" ; exit ;
+        printf "  print version  (-V|--version)\n" ; exit ;
     }
     printf "\nSome Environment:\n"
     for e in HOME INSIDE_EMACS TERM PWD SHELL PATH M5MOOEXEC M5LIBPATH; do
-        v="$(v='$'"$e" ; eval "printf \"%s\" $v")"
+        eval v=\$$e
         if test "$v"; then
             printf "  %s=%s\n" "$e" "$v"
         fi
@@ -822,45 +851,59 @@ describe_for_dryrun () {
             fi
         elif test "$template_db"; then
             printf "\nTemplate database (-t|--db):\n  %s.{top,bot}\n" "$template_db"
-            if test "$listen_fixed" || test "$listen_zcount" -gt 0; then
-                printf "  other listeners (-p|--listen):\n"
-                for z in $listen_fixed; do
-                    lname="$(eval printf "%s" '"$'"_listen_$z"'"')"
-                    if test "$shell_port" && test "$shell_port" -eq "$z"; then
-                        lname="$lname  (shell listener port)"
-                    fi
-                    printf "    %d -> %s\n" "$z" "$lname";
-                done ;
-                z=1
-                while test "$z" -le "$listen_zcount"; do
-                    lname="$(eval printf "%s" '"$'"_listen_z$z"'"')"
-                    if test "$shell_port" && test "$shell_listener" = "$lname" && test "$shell_port" -eq 0 ; then
-                        lname="$lname  (shell listener port)"
-                    fi
-                    printf "    0 -> %s\n" "$lname"
-                    z=$((z+1))
-                done
-            fi
+            is_first=:
+            for port in $listen_fixed; do
+                eval lname=\$_listen_$port
+                is_shell_port=false
+                test "$shell_port" && test "$shell_port" -eq "$port" &&
+                    is_shell_port=:
+                if $is_first ; then
+                    printf "  other listeners (-p|--listen):\n"
+                    is_first=false
+                fi
+                if $is_shell_port ; then
+                    lname="$lname  (shell listener port)"
+                fi
+                printf "    %d -> %s\n" "$port" "$lname"
+            done
+            port=0
+            z=1
+            while test "$z" -le "$listen_zcount"; do
+                eval lname=\$_listen_z$z
+                is_shell_port=false
+                test "$shell_port" && test "$shell_port" -eq "$port" &&
+                    test "$shell_listener" = "$lname" &&
+                    is_shell_port=:
+                if $is_first ; then
+                    printf "  other listeners (-p|--listen):\n"
+                    is_first=false
+                fi
+                if $is_shell_port ; then
+                    lname="$lname  (shell listener port)"
+                fi
+                printf "    %d -> %s\n" "$port" "$lname"
+                as_fn_arith $z \+ 1 && z=$as_val
+            done
             test "$do_player"   && printf "  (+P) adding fake 'player'\n"
             printf "  args = {%s}\n" "$moo_args"
             z=1
             while test "$z" -le "$code_count"  ; do
-                eval w='"$'"_code_what$z"'"'
-                eval v='"$'"_code_source$z"'"'
+                code_this="_code_source$z"
+                eval code_source=\$$code_this
+                eval w=\$_code_what$z
                 case $w in #(
-                    expr) :
-                        printf "  (-e) --expr= %s\n" "$v"
-                        ;; #(
                     file) :
-                        if test "$v" = "-"; then
-                            printf "  (-f) --code_file will be read from standard input\n"
-                        else
-                            printf "  (-f) --code_file= %s\n" "$v"
-                        fi
+                        printf "  (-f) --code_file= %s\n" "$code_source"
+                        ;; #(
+                    stdin) :
+                        printf "  (-f) --code_file will be read from standard input\n"
+                        ;; #(
+                    expr) :
+                        printf "  (-e) --expr= %s\n" "$code_source"
                         ;; #(
                     *) : ;;
                 esac
-                z=$((z+1))
+                as_fn_arith $z \+ 1 && z=$as_val
             done
             test "$do_shutdown" && printf "  (+H) adding shutdown()\n"
         fi
@@ -923,22 +966,16 @@ push_moo_listeners () {
             ;;
     esac
 
-    # TODO: convert to M4SH indirect variables
     if test "$lname" = "#0" && test -z "$moo_port"; then
         moo_port="$port"
     elif test "$port" -eq 0; then
-        listen_zcount=$((listen_zcount+1))
-        eval "_listen_z${listen_zcount}"='"$lname"'
+        as_fn_arith $listen_zcount \+ 1 && listen_zcount=$as_val
+        eval "_listen_z${listen_zcount}=\"\$lname\""
+    elif eval \${_listen_$port+:} false ; then
+        usage "--listen|-p:  multiple listeners at $port" ; return
     else
-        if test "$(eval printf "%s" '$'"_listen_$port")"; then
-            usage "--listen|-p:  multiple listeners at $port" ; return
-        fi
-        eval "_listen_$port"='"$lname"'
-        if test -z "$listen_fixed"; then
-            listen_fixed="$port"
-        else
-            listen_fixed="$listen_fixed $port"
-        fi
+        listen_fixed="$listen_fixed $port"
+        eval "_listen_$port=\"\$lname\""
     fi
 }
 
@@ -994,16 +1031,17 @@ push_lib_path () {
 }
 
 push_code () {
-    code_count=$((code_count+1))
     if test "$1" = 'file' && test "$2" = '-' ; then
-        if test "$do_stdin_code" ; then
-            usage "only one -f|--code-file can be standard input"
-        else
-            do_stdin_code="$code_count"
-        fi
+        $do_stdin_code &&
+          usage "only one -f|--code-file can be standard input"
+        do_stdin_code=:
+        w=stdin
+    else
+        w="$1"
     fi
-    eval "_code_what${code_count}="'"$'1'"'
-    eval "_code_source${code_count}="'"$'2'"'
+    as_fn_arith $code_count \+ 1 && code_count=$as_val
+    eval "_code_what${code_count}=\"\$w\""
+    eval "_code_source${code_count}=\"\$2\""
 }
 
 conflicts=
@@ -1313,7 +1351,7 @@ elif test "$template_db" ; then
 
     # add shell port to listeners if not there already
     #
-    lname="$(eval printf "%s" '$'"_listen_${shell_port}")"
+    eval lname=\$_listen_${shell_port}
     if test "$shell_port" && test "$shell_port" -gt 0 && test "$lname"; then
         shell_listener="$lname"
     elif test "$shell_port"; then
@@ -1332,14 +1370,18 @@ elif test "$template_db" ; then
     # resolve filenames
     z=1
     while test "$z" -le "$code_count"  ; do
-        eval w='"$'"_code_what$z"'"'
-        eval v='"$'"_code_source$z"'"'
-        if test "$w" = 'file' && test "$v" != '-' ; then
-            lib_find "$v" '.m5 .moo' ||
-                die "-f|--code-file not found: $v"
-            eval "_code_source${z}="'"$'full'"'
-        fi
-        z=$((z+1))
+        code_this="_code_source$z"
+        eval code_source=\$$code_this
+        eval w=\$_code_what$z
+        case $w in #(
+          file) :
+            lib_find "$code_source" '.m5 .moo' ||
+                die "-f|--code-file not found: $code_source"
+            eval "$code_this=\"\$full\"" ;; #(
+          *) :
+            ;;
+        esac
+        as_fn_arith $z \+ 1 && z=$as_val
     done
     lib_template_find "$template_db" ||
         die "-t|--db not found: $template_db"
